import { StyleSheet } from "react-native";

/**
 * Shared style sheet used across the app shell and screen components.
 *
 * @type {Object}
 */
export const styles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: "#000000" },
  appFrame: { flex: 1, paddingHorizontal: 16, paddingTop: 10, paddingBottom: 14 },
  phoneShell: {
    flex: 1,
    backgroundColor: "#000000",
    borderRadius: 30,
    borderWidth: 1,
    borderColor: "#1f1f1f",
    paddingHorizontal: 20,
    paddingTop: 20,
    paddingBottom: 92,
  },
  loaderWrap: { flex: 1, alignItems: "center", justifyContent: "center", gap: 12 },
  loaderText: { color: "#666666", fontSize: 14 },
  scrollContent: { paddingBottom: 36, gap: 18 },
  screenStack: { gap: 18 },
  label: { fontSize: 11, color: "#7a7a7a", textTransform: "uppercase", letterSpacing: 2, marginBottom: 10, fontWeight: "600" },
  title: { fontSize: 28, lineHeight: 32, color: "#111111", fontWeight: "600" },
  heroTitle: { fontSize: 40, lineHeight: 44, color: "#111111", fontWeight: "700", letterSpacing: -1.2, marginBottom: 2 },
  body: { fontSize: 15, lineHeight: 24, color: "#373737" },
  card: { backgroundColor: "#ffffff", borderWidth: 1, borderColor: "#dfdfdf", borderRadius: 24, padding: 20 },
  darkLabel: { color: "#d0d0d0" },
  darkTitle: { color: "#ffffff", marginBottom: 6 },
  darkBody: { color: "#ececec", marginBottom: 16 },
  headerRow: { flexDirection: "row", justifyContent: "space-between", alignItems: "flex-start", gap: 12 },
  flex: { flex: 1 },
  metricsRow: { flexDirection: "row", gap: 12 },
  metricValue: { fontSize: 25, color: "#111111", fontWeight: "700", letterSpacing: -0.8 },
  metricNote: { marginTop: 6, color: "#7a7a7a", fontSize: 13 },
  cardTitle: { fontSize: 22, lineHeight: 28, color: "#111111", fontWeight: "600" },
  infoLine: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 14,
    borderTopWidth: 1,
    borderTopColor: "#e7e7e7",
    paddingTop: 16,
    marginTop: 16,
  },
  infoLineFirst: { borderTopWidth: 0, paddingTop: 0, marginTop: 0 },
  infoTitle: { color: "#666666", fontSize: 14, flex: 1 },
  infoValue: { color: "#111111", fontSize: 14, fontWeight: "600", flex: 1, textAlign: "right" },
  buttonRow: { flexDirection: "row", gap: 12 },
  button: { minHeight: 58, borderRadius: 999, alignItems: "center", justifyContent: "center", paddingHorizontal: 20, flex: 1, borderWidth: 1, borderColor: "transparent" },
  primaryButtonText: { color: "#ffffff", fontSize: 15, fontWeight: "600" },
  lightButtonText: { color: "#111111", fontSize: 14, fontWeight: "600" },
  ghostButton: { backgroundColor: "#f1f1f1" },
  compactGhostButton: { backgroundColor: "#f1f1f1", minHeight: 42, paddingHorizontal: 16, flex: 0 },
  ghostButtonText: { color: "#111111", fontSize: 14, fontWeight: "600" },
  optionGrid: { flexDirection: "row", flexWrap: "wrap", gap: 12 },
  optionChip: { minHeight: 52, paddingHorizontal: 16, paddingVertical: 12, borderRadius: 18, backgroundColor: "#f3f3f3", justifyContent: "center", borderWidth: 1 },
  optionText: { color: "#555555", fontSize: 14, fontWeight: "600" },
  doneWeek: { backgroundColor: "#fafafa" },
  futureWeek: { opacity: 0.45 },
  currentWeek: { borderWidth: 2 },
  listRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 14,
    borderTopWidth: 1,
    borderTopColor: "#e7e7e7",
    paddingTop: 16,
    marginTop: 16,
    minHeight: 72,
  },
  listRowFirst: { borderTopWidth: 0, paddingTop: 0, marginTop: 0 },
  listTitle: { color: "#111111", fontSize: 15, fontWeight: "600", marginBottom: 4 },
  listCopy: { color: "#6b6b6b", fontSize: 13, lineHeight: 20 },
  listMeta: { color: "#7a7a7a", fontSize: 12, maxWidth: 72, textAlign: "right" },
  lockedText: { fontSize: 12, fontWeight: "600" },
  runScreen: { minHeight: 720, justifyContent: "center", gap: 18 },
  timer: { fontSize: 64, lineHeight: 68, color: "#111111", fontWeight: "700", letterSpacing: -2, textAlign: "center" },
  centeredTitle: { textAlign: "center" },
  centeredBody: { textAlign: "center", maxWidth: 320, alignSelf: "center" },
  timerPill: { alignSelf: "center", backgroundColor: "#f3f3f3", paddingHorizontal: 14, paddingVertical: 8, borderRadius: 999 },
  timerPillText: { color: "#666666", fontSize: 12, fontWeight: "600" },
  lockHint: { minHeight: 50, borderRadius: 999, alignItems: "center", justifyContent: "center", paddingHorizontal: 20 },
  stopHint: { textAlign: "center", marginTop: 12, fontSize: 13, fontWeight: "500" },
  chart: { flexDirection: "row", justifyContent: "space-between", alignItems: "flex-end", minHeight: 180, marginTop: 12 },
  barSlot: { flex: 1, alignItems: "center", justifyContent: "flex-end", gap: 8 },
  bar: { width: 16, borderRadius: 999, backgroundColor: "#111111" },
  barLabel: { color: "#777777", fontSize: 11 },
  pill: { backgroundColor: "#111111", color: "#ffffff", paddingHorizontal: 12, paddingVertical: 8, borderRadius: 999, overflow: "hidden", fontSize: 12, fontWeight: "600" },
  badgeRow: { flexDirection: "row", gap: 12, flex: 1 },
  badgeDot: { width: 42, height: 42, borderRadius: 21, borderWidth: 1, borderColor: "#dfdfdf", alignItems: "center", justifyContent: "center" },
  badgeDotText: { color: "#111111", fontSize: 13, fontWeight: "700" },
  lockedCard: { opacity: 0.45 },
  finishBadge: { width: 132, height: 132, borderRadius: 66, borderWidth: 1, borderColor: "#dfdfdf", alignItems: "center", justifyContent: "center", alignSelf: "center" },
  finishBadgeText: { color: "#111111", fontSize: 32, fontWeight: "700", letterSpacing: -1 },
  emptyCard: { alignItems: "flex-start", gap: 10 },
  emptyTitle: { fontSize: 20, lineHeight: 24, fontWeight: "700" },
  emptyNote: { fontSize: 14, lineHeight: 22 },
  tabBar: {
    position: "absolute",
    left: 16,
    right: 16,
    bottom: 16,
    flexDirection: "row",
    gap: 6,
    padding: 6,
    borderWidth: 1,
    borderColor: "#dfdfdf",
    borderRadius: 999,
    backgroundColor: "rgba(255,255,255,0.97)",
  },
  tab: { flex: 1, minHeight: 52, borderRadius: 999, alignItems: "center", justifyContent: "center" },
  tabText: { color: "#7a7a7a", fontSize: 13, fontWeight: "600" },
});
